"""empty message

Revision ID: 7396a376dece
Revises: 42e67e158013
Create Date: 2022-12-20 23:32:35.226586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7396a376dece'
down_revision = '42e67e158013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###
