"""empty message

Revision ID: 75812e87a5fa
Revises: f4f47080bb1b
Create Date: 2022-07-25 12:53:58.997567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75812e87a5fa'
down_revision = 'f4f47080bb1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patrons')
    op.drop_column('users', 'email')
    op.drop_column('wait_reactions', 'uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wait_reactions', sa.Column('uid', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('patrons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='patrons_pkey')
    )
    # ### end Alembic commands ###
