"""empty message

Revision ID: 831446800c46
Revises: 
Create Date: 2022-11-29 13:38:36.869947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831446800c46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Text(), nullable=True),
    sa.Column('cur_message_link', sa.Text(), nullable=True),
    sa.Column('num_referals', sa.Integer(), nullable=True),
    sa.Column('chapter_message_links', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('wait_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('start_of_chapter_name', sa.Text(), nullable=True),
    sa.Column('start_msg', sa.Boolean(), nullable=True),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.Column('time_typing', sa.Float(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('next_msg', sa.Text(), nullable=True),
    sa.Column('wait_reaction_id', sa.Integer(), nullable=True),
    sa.Column('referal_block', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_msg'], ['messages.link'], ),
    sa.ForeignKeyConstraint(['wait_reaction_id'], ['wait_reactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('wait_reaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wait_reaction_id'], ['wait_reactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_flags',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('users_id', 'flag_id')
    )
    op.create_table('buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parrent_message_link', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('next_message_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['next_message_link'], ['messages.link'], ),
    sa.ForeignKeyConstraint(['parrent_message_link'], ['messages.link'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('tg_id', sa.Text(), nullable=True),
    sa.Column('parrent_message_link', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parrent_message_link'], ['messages.link'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_rm_flags',
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flag_id', 'message_id')
    )
    op.create_table('message_set_flags',
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flag_id', 'message_id')
    )
    op.create_table('button_condition_flags',
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('button_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flag_id', 'button_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('button_condition_flags')
    op.drop_table('message_set_flags')
    op.drop_table('message_rm_flags')
    op.drop_table('media')
    op.drop_table('buttons')
    op.drop_table('user_flags')
    op.drop_table('reactions')
    op.drop_table('messages')
    op.drop_table('wait_reactions')
    op.drop_table('users')
    op.drop_table('flags')
    # ### end Alembic commands ###
