"""empty message

Revision ID: 8579103dffab
Revises: 7396a376dece
Create Date: 2022-12-20 23:42:06.200817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8579103dffab'
down_revision = '7396a376dece'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_message_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_message_date')
    # ### end Alembic commands ###
