"""empty message

Revision ID: f2906e08ae5d
Revises: 75812e87a5fa
Create Date: 2022-07-25 14:41:49.996268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2906e08ae5d'
down_revision = '75812e87a5fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('start_of_chapter_name', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('chapter_message_links', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chapter_message_links')
    op.drop_column('messages', 'start_of_chapter_name')
    # ### end Alembic commands ###
