"""empty message

Revision ID: f4f47080bb1b
Revises: ec5c078b1296
Create Date: 2022-07-22 12:33:50.483805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f47080bb1b'
down_revision = 'ec5c078b1296'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('time_typing', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'messages', ['link'])
    op.drop_column('messages', 'speed_type')
    op.add_column('users', sa.Column('cur_message_link', sa.Text(), nullable=True))
    op.drop_column('users', 'cur_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cur_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'cur_message_link')
    op.add_column('messages', sa.Column('speed_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_column('messages', 'time_typing')
    # ### end Alembic commands ###
